<?php

namespace Database\Seeders;

use App\Models\BlogPost;
use App\Models\DestinationRoute;
use App\Models\LeadershipMember;
use App\Models\Page;
use App\Models\Partner;
use App\Models\SiteSetting;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::query()->updateOrCreate(
            ['email' => 'info@busterminal.ge'],
            [
                'name' => 'Buster Terminal Admin',
                'password' => 'Admin2026!!!',
                'email_verified_at' => now(),
                'is_admin' => true,
            ],
        );

        SiteSetting::query()->updateOrCreate(
            ['key' => 'primary'],
            [
                'hero_ka' => [
                    'badge' => '24/7 • გემსახურებით 1973 წლიდან',
                    'title1' => 'შენი გზა მთელს საქართველოში',
                    'title2' => 'და საზღვრებს გარეთ',
                    'description' => '50 წელზე მეტი თქვენს სამსახურში. ავტობუსებით და მიკროავტობუსებით შიდა და საერთაშორისო მიმართულებებით მგზავრობა.',
                    'location' => 'გულიას ქ. 5, თბილისი 0114, საქართველო',
                    'stats' => [
                        ['value' => '50+', 'label' => 'წელი შენს სამსახურში'],
                        ['value' => '100+', 'label' => 'ყოველდღიური რეისები'],
                        ['value' => '25+', 'label' => 'მიმართულება'],
                        ['value' => '500K+', 'label' => 'მგზავრი წელიწადში'],
                    ],
                ],
                'hero_en' => [
                    'badge' => 'Open 24/7 • Serving Since 1973',
                    'title1' => 'Your Gateway to',
                    'title2' => 'Georgia and Beyond',
                    'description' => 'Over 50 years of connecting travelers across Georgia and beyond. Bus and microbus transportation to domestic and international destinations.',
                    'location' => '5 Gulia St, Tbilisi 0114, Georgia',
                    'stats' => [
                        ['value' => '50+', 'label' => 'Years of Service'],
                        ['value' => '100+', 'label' => 'Daily Departures'],
                        ['value' => '25+', 'label' => 'Destinations'],
                        ['value' => '500K+', 'label' => 'Passengers Annually'],
                    ],
                ],
                'hero_ru' => [
                    'badge' => 'Открыто 24/7 • Работаем с 1973 года',
                    'title1' => 'Ваш путь по',
                    'title2' => 'Грузии и за ее пределы',
                    'description' => 'Более 50 лет соединяем путешественников по Грузии и за ее пределами. Автобусные и микроавтобусные рейсы по внутренним и международным направлениям.',
                    'location' => 'ул. Гулиа 5, Тбилиси 0114, Грузия',
                    'stats' => [
                        ['value' => '50+', 'label' => 'Лет работы'],
                        ['value' => '100+', 'label' => 'Рейсов в день'],
                        ['value' => '25+', 'label' => 'Направлений'],
                        ['value' => '500K+', 'label' => 'Пассажиров в год'],
                    ],
                ],
                'about_ka' => [
                    'badge' => 'ჩვენს შესახებ',
                    'title1' => 'თბილისი ცენტრალური',
                    'title2' => 'ავტოსადგური',
                    'description' => 'თბილისის ცენტრალური ავტოსადგური გაიხსნა 1973 წელს. ტერმინალი მდებარეობს თბილისის სამხრეთ-აღმოსავლეთ ნაწილში, გულიას მოედნისა და აკვედუკის ხიდის მახლობლად. სულ 3.5 ჰექტარი ფართობი უშუალოდ ესაზღვრება მტკვრის მარჯვენა ნაპირს. ავტოსადგური გათვლილია დაახლოებით 18,500 მგზავრზე დღეში.',
                    'stats' => [
                        ['value' => '1973', 'label' => 'დაარსდა'],
                        ['value' => '24/7', 'label' => 'მუშაობა'],
                        ['value' => '500K+', 'label' => 'მგზავრი წელიწადში'],
                        ['value' => '3.5', 'label' => 'ჰექტარი'],
                    ],
                    'gallery' => [
                        ['src' => 'cms/gallery/terminal-interior.jpg', 'alt' => 'ტერმინალის ინტერიერი'],
                        ['src' => 'cms/gallery/terminal-building.jpg', 'alt' => 'ტერმინალის შენობა'],
                        ['src' => 'cms/gallery/terminal-exterior.jpg', 'alt' => 'ტერმინალის ექსტერიერი'],
                        ['src' => 'cms/gallery/terminal-historic.webp', 'alt' => 'ისტორიული ხედი'],
                    ],
                    'features' => [
                        ['icon' => 'building2', 'title' => 'თანამედროვე ინფრასტრუქტურა', 'description' => 'რესტორნები, კაფეები, მაღაზიები და სასტუმრო.'],
                        ['icon' => 'users', 'title' => 'პროფესიონალური მომსახურება', 'description' => 'ერთგული პერსონალი თქვენი მოგზაურობისთვის.'],
                        ['icon' => 'shield', 'title' => 'უსაფრთხოება', 'description' => 'ყველა პარტნიორი აკმაყოფილებს უსაფრთხოების სტანდარტებს.'],
                    ],
                ],
                'about_en' => [
                    'badge' => 'About Us',
                    'title1' => 'Tbilisi Central',
                    'title2' => 'Bus Terminal',
                    'description' => 'In 1973, a new complex of Tbilisi Central Bus Terminal was realized in Ortachala. The terminal is located in the south-eastern part of Tbilisi, near Gulia Square and Aqueduct Bridge. The bus terminal is designed to accommodate around 18,500 passengers per day.',
                    'stats' => [
                        ['value' => '1973', 'label' => 'Established'],
                        ['value' => '24/7', 'label' => 'Operations'],
                        ['value' => '500K+', 'label' => 'Yearly Passengers'],
                        ['value' => '3.5', 'label' => 'Hectares'],
                    ],
                    'gallery' => [
                        ['src' => 'cms/gallery/terminal-interior.jpg', 'alt' => 'Terminal Interior'],
                        ['src' => 'cms/gallery/terminal-building.jpg', 'alt' => 'Terminal Building'],
                        ['src' => 'cms/gallery/terminal-exterior.jpg', 'alt' => 'Terminal Exterior'],
                        ['src' => 'cms/gallery/terminal-historic.webp', 'alt' => 'Historic View'],
                    ],
                    'features' => [
                        ['icon' => 'building2', 'title' => 'Modern Facilities', 'description' => 'Restaurants, cafes, shops, and on-site hotel accommodations.'],
                        ['icon' => 'users', 'title' => 'Professional Service', 'description' => 'Dedicated staff committed to making your journey pleasant.'],
                        ['icon' => 'shield', 'title' => 'Safety First', 'description' => 'All partner companies meet strict safety standards.'],
                    ],
                ],
                'about_ru' => [
                    'badge' => 'О нас',
                    'title1' => 'Тбилисский центральный',
                    'title2' => 'автовокзал',
                    'description' => 'Тбилисский центральный автовокзал открыт в 1973 году. Терминал расположен в юго-восточной части Тбилиси, рядом с площадью Гулиа и Акведуком. Автовокзал рассчитан примерно на 18 500 пассажиров в день.',
                    'stats' => [
                        ['value' => '1973', 'label' => 'Основан'],
                        ['value' => '24/7', 'label' => 'Работа'],
                        ['value' => '500K+', 'label' => 'Пассажиров в год'],
                        ['value' => '3.5', 'label' => 'Гектара'],
                    ],
                    'gallery' => [
                        ['src' => 'cms/gallery/terminal-interior.jpg', 'alt' => 'Интерьер терминала'],
                        ['src' => 'cms/gallery/terminal-building.jpg', 'alt' => 'Здание терминала'],
                        ['src' => 'cms/gallery/terminal-exterior.jpg', 'alt' => 'Экстерьер терминала'],
                        ['src' => 'cms/gallery/terminal-historic.webp', 'alt' => 'Исторический вид'],
                    ],
                    'features' => [
                        ['icon' => 'building2', 'title' => 'Современная инфраструктура', 'description' => 'Рестораны, кафе, магазины и гостиница на территории.'],
                        ['icon' => 'users', 'title' => 'Профессиональный сервис', 'description' => 'Команда, которая делает поездку комфортной.'],
                        ['icon' => 'shield', 'title' => 'Безопасность', 'description' => 'Все партнеры соответствуют строгим стандартам безопасности.'],
                    ],
                ],
                'contact_ka' => [
                    'badge' => 'კონტაქტი',
                    'title1' => 'დაგვიკავშირდით',
                    'title2' => '',
                    'description' => 'ნებისმიერ დროს შეგიძლიათ დაგვიკავშირდეთ ქვემოთ მოცემული არხებით.',
                    'addressLabel' => 'მისამართი',
                    'addressValue' => 'გულიას ქ. 5, თბილისი 0114, საქართველო',
                    'addressNote' => 'ორტაჭალა, გულიას მოედნის მიმდებარედ',
                    'phoneLabel' => 'ტელეფონი',
                    'phone' => '+995 596 10 22 22',
                    'emailLabel' => 'ელ.ფოსტა',
                    'email' => 'info@busterminal.ge',
                    'hoursLabel' => 'სამუშაო საათები',
                    'terminalLabel' => 'ტერმინალი',
                    'terminalHours' => '24/7',
                    'infoDeskLabel' => 'საინფორმაციო',
                    'infoDeskHours' => '06:00 - 22:00',
                    'followUsLabel' => 'გამოგვყევით',
                    'facebookUrl' => 'https://www.facebook.com/TBILISIBUSTERMINAL',
                    'instagramUrl' => 'https://www.instagram.com/tbilisibusterminal',
                ],
                'contact_en' => [
                    'badge' => 'Contact Us',
                    'title1' => 'Get in',
                    'title2' => ' Touch',
                    'description' => 'We would love to hear from you. Feel free to reach out using the details below.',
                    'addressLabel' => 'Address',
                    'addressValue' => '5 Gulia St, Tbilisi 0114, Georgia',
                    'addressNote' => 'Ortachala, near Gulia Square',
                    'phoneLabel' => 'Phone',
                    'phone' => '+995 596 10 22 22',
                    'emailLabel' => 'Email',
                    'email' => 'info@busterminal.ge',
                    'hoursLabel' => 'Working Hours',
                    'terminalLabel' => 'Terminal',
                    'terminalHours' => '24/7',
                    'infoDeskLabel' => 'Information Desk',
                    'infoDeskHours' => '06:00 - 22:00',
                    'followUsLabel' => 'Follow Us',
                    'facebookUrl' => 'https://www.facebook.com/TBILISIBUSTERMINAL',
                    'instagramUrl' => 'https://www.instagram.com/tbilisibusterminal',
                ],
                'contact_ru' => [
                    'badge' => 'Контакты',
                    'title1' => 'Свяжитесь',
                    'title2' => ' с нами',
                    'description' => 'Мы будем рады вашему сообщению. Используйте контакты ниже.',
                    'addressLabel' => 'Адрес',
                    'addressValue' => 'ул. Гулиа 5, Тбилиси 0114, Грузия',
                    'addressNote' => 'Ортачала, рядом с площадью Гулиа',
                    'phoneLabel' => 'Телефон',
                    'phone' => '+995 596 10 22 22',
                    'emailLabel' => 'Email',
                    'email' => 'info@busterminal.ge',
                    'hoursLabel' => 'Часы работы',
                    'terminalLabel' => 'Терминал',
                    'terminalHours' => '24/7',
                    'infoDeskLabel' => 'Инфо-стойка',
                    'infoDeskHours' => '06:00 - 22:00',
                    'followUsLabel' => 'Мы в соцсетях',
                    'facebookUrl' => 'https://www.facebook.com/TBILISIBUSTERMINAL',
                    'instagramUrl' => 'https://www.instagram.com/tbilisibusterminal',
                ],
                'footer_ka' => [
                    'brandTitle' => 'TBILISI',
                    'brandSubtitle' => 'Central Bus Terminal',
                    'description' => 'ვაერთიანებთ საქართველოს 1973 წლიდან. თქვენი სანდო პარტნიორი უსაფრთხო და კომფორტული მგზავრობისთვის.',
                    'privacyLabel' => 'კონფიდენციალურობა',
                    'termsLabel' => 'წესები და პირობები',
                    'popularRoutes' => ['თბილისი - ბათუმი', 'თბილისი - ქუთაისი', 'თბილისი - ზუგდიდი', 'თბილისი - მესტია', 'თბილისი - სტამბული'],
                ],
                'footer_en' => [
                    'brandTitle' => 'TBILISI',
                    'brandSubtitle' => 'Central Bus Terminal',
                    'description' => 'Connecting Georgia since 1973. Your trusted partner for safe and comfortable travel across the country and beyond.',
                    'privacyLabel' => 'Privacy Policy',
                    'termsLabel' => 'Terms of Service',
                    'popularRoutes' => ['Tbilisi - Batumi', 'Tbilisi - Kutaisi', 'Tbilisi - Zugdidi', 'Tbilisi - Mestia', 'Tbilisi - Istanbul'],
                ],
                'footer_ru' => [
                    'brandTitle' => 'TBILISI',
                    'brandSubtitle' => 'Central Bus Terminal',
                    'description' => 'Соединяем Грузию с 1973 года. Ваш надежный партнер для безопасных и комфортных поездок.',
                    'privacyLabel' => 'Политика конфиденциальности',
                    'termsLabel' => 'Условия использования',
                    'popularRoutes' => ['Тбилиси - Батуми', 'Тбилиси - Кутаиси', 'Тбилиси - Зугдиди', 'Тбилиси - Местия', 'Тбилиси - Стамбул'],
                ],
            ],
        );

        foreach ([
            [
                'slug' => 'batumi',
                'route_type' => 'domestic',
                'city_ka' => 'ბათუმი',
                'city_en' => 'Batumi',
                'city_ru' => 'Батуми',
                'duration' => '5-6h',
                'price_from' => '35 GEL',
                'provider_links' => [
                    ['name' => 'Metro Georgia', 'url' => 'https://metrogeorgia.ge'],
                    ['name' => 'Omnibus', 'url' => 'https://omnibusexpress.ge'],
                    ['name' => 'CityBus', 'url' => 'https://citybus.ge'],
                ],
                'show_in_footer' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'kutaisi',
                'route_type' => 'domestic',
                'city_ka' => 'ქუთაისი',
                'city_en' => 'Kutaisi',
                'city_ru' => 'Кутаиси',
                'duration' => '3-4h',
                'price_from' => '18 GEL',
                'provider_links' => [
                    ['name' => 'Omnibus', 'url' => 'https://omnibusexpress.ge'],
                    ['name' => 'CityBus', 'url' => 'https://citybus.ge'],
                    ['name' => 'Metro Georgia', 'url' => 'https://metrogeorgia.ge'],
                ],
                'show_in_footer' => true,
                'sort_order' => 20,
            ],
            [
                'slug' => 'zugdidi',
                'route_type' => 'domestic',
                'city_ka' => 'ზუგდიდი',
                'city_en' => 'Zugdidi',
                'city_ru' => 'Зугдиди',
                'duration' => '5-6h',
                'price_from' => '30 GEL',
                'provider_links' => [
                    ['name' => 'Omnibus', 'url' => 'https://omnibusexpress.ge'],
                    ['name' => 'Metro Georgia', 'url' => 'https://metrogeorgia.ge'],
                ],
                'show_in_footer' => true,
                'sort_order' => 30,
            ],
            [
                'slug' => 'istanbul',
                'route_type' => 'international',
                'city_ka' => 'სტამბული',
                'city_en' => 'Istanbul',
                'city_ru' => 'Стамбул',
                'country_ka' => 'თურქეთი',
                'country_en' => 'Turkey',
                'country_ru' => 'Турция',
                'duration' => '18h',
                'price_from' => '120 GEL',
                'provider_links' => [
                    ['name' => 'Luks Karadeniz', 'url' => 'https://lukskaradeniz.com'],
                    ['name' => 'Metro Georgia', 'url' => 'https://metrogeorgia.ge'],
                    ['name' => 'Obilet', 'url' => 'https://obilet.com'],
                ],
                'show_in_footer' => true,
                'sort_order' => 40,
            ],
            [
                'slug' => 'yerevan',
                'route_type' => 'international',
                'city_ka' => 'ერევანი',
                'city_en' => 'Yerevan',
                'city_ru' => 'Ереван',
                'country_ka' => 'სომხეთი',
                'country_en' => 'Armenia',
                'country_ru' => 'Армения',
                'duration' => '5h',
                'price_from' => '35 GEL',
                'provider_links' => [
                    ['name' => 'TKT.ge', 'url' => 'https://tkt.ge/ortachala'],
                ],
                'show_in_footer' => true,
                'sort_order' => 50,
            ],
        ] as $route) {
            DestinationRoute::query()->updateOrCreate(['slug' => $route['slug']], $route);
        }

        foreach ([
            [
                'name' => 'Omnibus',
                'description_ka' => 'საიმედო, კომფორტული და ეფექტური ავტობუსის მომსახურება სხვადასხვა მიმართულებით.',
                'description_en' => 'Reliable, comfortable, and efficient bus services to various destinations.',
                'description_ru' => 'Надежные, комфортные и эффективные автобусные рейсы в различные направления.',
                'routes_ka' => 'ქუთაისი, ბათუმი, ზუგდიდი',
                'routes_en' => 'Kutaisi, Batumi, Zugdidi',
                'routes_ru' => 'Кутаиси, Батуми, Зугдиди',
                'website' => 'https://omnibusexpress.ge/',
                'logo_url' => 'cms/partners/omnibus.png',
                'sort_order' => 10,
            ],
            [
                'name' => 'CityBus',
                'description_ka' => 'საიმედო, კომფორტული და ეფექტური ავტობუსის მომსახურება სხვადასხვა მიმართულებით.',
                'description_en' => 'Reliable, comfortable, and efficient bus services to various destinations.',
                'description_ru' => 'Надежные, комфортные и эффективные автобусные рейсы в различные направления.',
                'routes_ka' => 'ბათუმი, ქუთაისი',
                'routes_en' => 'Batumi, Kutaisi',
                'routes_ru' => 'Батуми, Кутаиси',
                'website' => 'https://citybus.ge',
                'logo_url' => 'cms/partners/citybus.png',
                'sort_order' => 20,
            ],
            [
                'name' => 'Metro Georgia',
                'description_ka' => 'საიმედო, კომფორტული და ეფექტური ავტობუსის მომსახურება სხვადასხვა მიმართულებით.',
                'description_en' => 'Reliable, comfortable, and efficient bus services to various destinations.',
                'description_ru' => 'Надежные, комфортные и эффективные автобусные рейсы в различные направления.',
                'routes_ka' => 'ბათუმი, ქუთაისი, ზუგდიდი, სტამბული, იზმირი',
                'routes_en' => 'Batumi, Kutaisi, Zugdidi, Istanbul, Izmir',
                'routes_ru' => 'Батуми, Кутаиси, Зугдиди, Стамбул, Измир',
                'website' => 'https://www.metrogeorgia.ge/',
                'logo_url' => 'cms/partners/metro-georgia.jpg',
                'sort_order' => 30,
            ],
            [
                'name' => 'Luks Karadeniz',
                'description_ka' => 'საერთაშორისო მარშრუტები საიმედო, კომფორტული და ეფექტური მომსახურებით.',
                'description_en' => 'International routes with reliable, comfortable, and efficient service.',
                'description_ru' => 'Международные маршруты с надежным, комфортным и эффективным обслуживанием.',
                'routes_ka' => 'სტამბული, ანკარა, ტრაბზონი',
                'routes_en' => 'Istanbul, Ankara, Trabzon',
                'routes_ru' => 'Стамбул, Анкара, Трабзон',
                'website' => 'https://lukskaradeniz.com/',
                'logo_url' => 'cms/partners/luks-karadeniz.svg',
                'sort_order' => 40,
            ],
            [
                'name' => 'TKT.ge',
                'description_ka' => 'შერჩეული შიდა და საერთაშორისო მარშრუტების ბილეთები.',
                'description_en' => 'Selected domestic and international route tickets.',
                'description_ru' => 'Билеты на избранные внутренние и международные маршруты.',
                'routes_ka' => 'კახეთი, ბორჯომი, ერევანი და სხვა',
                'routes_en' => 'Kakheti, Borjomi, Yerevan and more',
                'routes_ru' => 'Кахетия, Боржоми, Ереван и другие',
                'website' => 'https://www.tkt.ge/ortachala',
                'logo_url' => 'cms/partners/tkt-ge.png',
                'sort_order' => 50,
            ],
        ] as $partner) {
            Partner::query()->updateOrCreate(
                ['name' => $partner['name']],
                $partner + [
                    'seo_title_ka' => "{$partner['name']} | სატრანსპორტო პარტნიორი | თბილისის ცენტრალური ავტოსადგური",
                    'seo_title_en' => "{$partner['name']} | Transport Partner | Tbilisi Central Bus Terminal",
                    'seo_title_ru' => "{$partner['name']} | Транспортный партнёр | Тбилисский центральный автовокзал",
                    'seo_description_ka' => $partner['description_ka'],
                    'seo_description_en' => $partner['description_en'],
                    'seo_description_ru' => $partner['description_ru'],
                    'seo_keywords_ka' => "{$partner['name']}, ავტობუსი, პარტნიორი, ბილეთები",
                    'seo_keywords_en' => "{$partner['name']}, bus, partner, tickets",
                    'seo_keywords_ru' => "{$partner['name']}, автобус, партнёр, билеты",
                    'seo_image_url' => $partner['logo_url'] ?? null,
                    'noindex' => false,
                ],
            );
        }

        foreach ([
            ['name' => 'Giorgi Suladze', 'role_key' => 'chairman', 'phone' => '+995 591 52 25 25', 'linkedin' => 'https://www.linkedin.com/in/giorgisuladze', 'sort_order' => 10],
            ['name' => 'Merab Machavariani', 'role_key' => 'deputyChairman', 'phone' => '+995 599 96 10 10', 'linkedin' => 'https://www.linkedin.com/in/merab-machavariani-046a46376', 'sort_order' => 20],
            ['name' => 'Temur Jamrishvili', 'role_key' => 'ceo', 'phone' => '+995 599 17 24 95', 'sort_order' => 30],
            ['name' => 'Konstantine Rusadze', 'role_key' => 'deputyCeo', 'phone' => '+995 577 58 23 23', 'sort_order' => 40],
            ['name' => 'Nick Shonia', 'role_key' => 'coo', 'phone' => '+995 597 12 32 25', 'linkedin' => 'https://www.linkedin.com/in/nick-shonia-2209b434/', 'sort_order' => 50],
            ['name' => 'Nana Sturua', 'role_key' => 'chiefAccountant', 'phone' => '+995 555 17 45 55', 'sort_order' => 60],
        ] as $leader) {
            LeadershipMember::query()->updateOrCreate(
                ['name' => $leader['name']],
                $leader + ['whatsapp_enabled' => true, 'published' => true],
            );
        }

        Page::query()->updateOrCreate(
            ['slug' => 'terminal-history'],
            [
                'page_type' => 'custom',
                'route_path' => '/page/terminal-history',
                'nav_label_ka' => 'ისტორია',
                'nav_label_en' => 'History',
                'nav_label_ru' => 'История',
                'title_ka' => 'თბილისის ცენტრალური ავტოსადგურის ისტორია',
                'title_en' => 'History of Tbilisi Central Bus Terminal',
                'title_ru' => 'История Тбилисского центрального автовокзала',
                'excerpt_ka' => '1973 წლიდან დღემდე ტერმინალის განვითარების მოკლე ქრონიკა.',
                'excerpt_en' => 'A short timeline of the terminal from 1973 to today.',
                'excerpt_ru' => 'Краткая история развития терминала с 1973 года по сегодняшний день.',
                'content_ka' => '<p>თბილისის ცენტრალური ავტოსადგური 1973 წლიდან ემსახურება მგზავრებს და დღემდე ერთ-ერთი მთავარი სატრანსპორტო კვანძია.</p><p>ახალი CMS-ით ამ გვერდის შიგთავსს უკვე ადმინიდან მართავ.</p>',
                'content_en' => '<p>Tbilisi Central Bus Terminal has served passengers since 1973 and remains one of the city&apos;s main transport hubs.</p><p>This page is now managed from the admin panel.</p>',
                'content_ru' => '<p>Тбилисский центральный автовокзал обслуживает пассажиров с 1973 года и остается одним из главных транспортных узлов города.</p><p>Содержимое этой страницы теперь управляется из админ-панели.</p>',
                'cover_image_url' => 'cms/gallery/terminal-building.jpg',
                'seo_title_ka' => 'თბილისის ცენტრალური ავტოსადგურის ისტორია',
                'seo_title_en' => 'History of Tbilisi Central Bus Terminal',
                'seo_title_ru' => 'История Тбилисского центрального автовокзала',
                'seo_description_ka' => '1973 წლიდან დღემდე ტერმინალის განვითარების მოკლე ქრონიკა.',
                'seo_description_en' => 'A short timeline of the terminal from 1973 to today.',
                'seo_description_ru' => 'Краткая история развития терминала с 1973 года по сегодняшний день.',
                'seo_keywords_ka' => 'ისტორია, ავტოსადგური, თბილისი, ტერმინალი',
                'seo_keywords_en' => 'history, terminal, Tbilisi, bus station',
                'seo_keywords_ru' => 'история, терминал, Тбилиси, автовокзал',
                'seo_image_url' => 'cms/gallery/terminal-building.jpg',
                'noindex' => false,
                'published' => true,
                'show_in_navigation' => true,
                'sort_order' => 10,
            ],
        );

        BlogPost::query()->where('slug', 'welcome-to-the-new-admin')->delete();

        foreach ([
            [
                'slug' => 'omnibus-popular-routes-from-tbilisi',
                'title_ka' => 'Omnibus: პოპულარული შიდა მარშრუტები თბილისიდან',
                'title_en' => 'Omnibus: Popular domestic routes from Tbilisi',
                'title_ru' => 'Omnibus: Популярные внутренние маршруты из Тбилиси',
                'excerpt_ka' => 'Omnibus ონლაინ დაჯავშნას და მოთხოვნად შიდა რეისებს აერთიანებს ერთ პრაქტიკულ სერვისში.',
                'excerpt_en' => 'Omnibus combines online booking with practical intercity routes across Georgia.',
                'excerpt_ru' => 'Omnibus сочетает онлайн-бронирование с удобными междугородними маршрутами по Грузии.',
                'content_ka' => '<p>Omnibus ჩვენი ტერმინალის ერთ-ერთი ის პარტნიორია, რომელიც მგზავრებს ყოველდღიურად მოთხოვნად შიდა მიმართულებებზე აძლევს არჩევანს. კომპანიის ოფიციალური ვებგვერდი ონლაინ ბილეთის მოძიებასა და დაჯავშნას ამარტივებს, რაც განსაკუთრებით კომფორტულია მაშინ, როცა გზა წინასწარ გაქვს დასაგეგმი.</p><p>თბილისის ცენტრალური ავტოსადგურიდან Omnibus-ის როლი კარგად ჩანს ბათუმის, ქუთაისისა და ზუგდიდის მიმართულებებზე. ასეთი რეისებისას ყველაზე მნიშვნელოვანია მკაფიო ინფორმაცია, მარტივი დაჯავშნა და ნაცნობ მარშრუტზე სწრაფი გადაწყვეტილების მიღება.</p><ul><li>პოპულარული შიდა მიმართულებები დასავლეთ საქართველოსკენ</li><li>ონლაინ ბილეთის ძიება და ყიდვა ოფიციალური პლატფორმიდან</li><li>პრაქტიკული არჩევანი როგორც წინასწარ დაგეგმილი, ისე სწრაფი მგზავრობისთვის</li></ul><p>თუ გინდა ნაცნობ მიმართულებაზე ბილეთი ზედმეტი სირთულის გარეშე იპოვო, Omnibus ერთ-ერთი ყველაზე პრაქტიკული ვარიანტია ჩვენი ტერმინალიდან გამგზავრებისთვის.</p><p><a href="https://omnibusexpress.ge/" target="_blank" rel="noopener noreferrer">ოფიციალური ვებგვერდი</a></p>',
                'content_en' => '<p>Omnibus is one of the partners at our terminal that gives passengers a practical option on some of the busiest domestic routes. Its official website is built around simple route search and online booking, which is especially useful when you want to plan a trip in advance.</p><p>From Tbilisi Central Bus Terminal, Omnibus stands out on routes to Batumi, Kutaisi, and Zugdidi. On these high-demand corridors, clear information and a quick booking flow make a real difference for travelers.</p><ul><li>Popular domestic routes toward western Georgia</li><li>Online ticket search and purchase from the official platform</li><li>A practical choice for both planned and last-minute trips</li></ul><p>If you want a straightforward booking experience for a familiar route, Omnibus is one of the most useful options departing from our terminal.</p><p><a href="https://omnibusexpress.ge/" target="_blank" rel="noopener noreferrer">Official website</a></p>',
                'content_ru' => '<p>Omnibus — один из партнеров нашего терминала, который предлагает пассажирам удобный выбор на самых востребованных внутренних направлениях. Официальный сайт компании ориентирован на простой поиск рейса и онлайн-бронирование, что особенно удобно при заранее запланированной поездке.</p><p>Из Тбилисского центрального автовокзала Omnibus особенно заметен на маршрутах в Батуми, Кутаиси и Зугдиди. На таких популярных направлениях важны понятная информация и быстрый процесс покупки билета.</p><ul><li>Популярные внутренние направления на запад Грузии</li><li>Поиск и покупка билета на официальной платформе</li><li>Практичный выбор и для запланированных, и для срочных поездок</li></ul><p>Если вам нужен простой способ быстро купить билет на знакомый маршрут, Omnibus — один из самых удобных вариантов отправления из нашего терминала.</p><p><a href="https://omnibusexpress.ge/" target="_blank" rel="noopener noreferrer">Официальный сайт</a></p>',
                'cover_image_url' => 'cms/partners/omnibus.png',
                'seo_title_ka' => 'Omnibus: პოპულარული შიდა მარშრუტები თბილისიდან',
                'seo_title_en' => 'Omnibus: Popular domestic routes from Tbilisi',
                'seo_title_ru' => 'Omnibus: Популярные внутренние маршруты из Тбилиси',
                'seo_description_ka' => 'მოკლე მიმოხილვა Omnibus-ის სერვისზე, ონლაინ დაჯავშნასა და თბილისიდან ბათუმის, ქუთაისისა და ზუგდიდის მიმართულებებზე.',
                'seo_description_en' => 'A short overview of Omnibus, its online booking flow, and popular routes from Tbilisi to Batumi, Kutaisi, and Zugdidi.',
                'seo_description_ru' => 'Краткий обзор сервиса Omnibus, онлайн-бронирования и популярных маршрутов из Тбилиси в Батуми, Кутаиси и Зугдиди.',
                'seo_keywords_ka' => 'Omnibus, თბილისი, ბათუმი, ქუთაისი, ზუგდიდი, ავტობუსი, ბილეთი',
                'seo_keywords_en' => 'Omnibus, Tbilisi, Batumi, Kutaisi, Zugdidi, bus ticket',
                'seo_keywords_ru' => 'Omnibus, Тбилиси, Батуми, Кутаиси, Зугдиди, автобус, билет',
                'seo_image_url' => 'cms/partners/omnibus.png',
                'noindex' => false,
                'author_name' => 'Buster Terminal',
                'published_at' => Carbon::create(2026, 3, 16, 13, 0, 0),
                'published' => true,
                'sort_order' => 10,
            ],
            [
                'slug' => 'citybus-simple-and-comfortable-city-to-city-travel',
                'title_ka' => 'CityBus: მარტივი და კომფორტული მგზავრობა ბათუმსა და ქუთაისში',
                'title_en' => 'CityBus: Simple and comfortable travel to Batumi and Kutaisi',
                'title_ru' => 'CityBus: Простая и комфортная поездка в Батуми и Кутаиси',
                'excerpt_ka' => 'CityBus შიდა მარშრუტებზე ციფრულად ხელმისაწვდომ და მგზავრზე ორიენტირებულ სერვისს გვთავაზობს.',
                'excerpt_en' => 'CityBus offers a digital-first and passenger-friendly approach on key domestic routes.',
                'excerpt_ru' => 'CityBus предлагает цифровой и удобный для пассажира подход на ключевых внутренних маршрутах.',
                'content_ka' => '<p>CityBus იმ პარტნიორებს შორისაა, რომლებიც მგზავრს სწრაფად აძლევს გადაწყვეტილების მიღების შესაძლებლობას: ნახო რეისი, გადაამოწმო ინფორმაცია და დაგეგმო გასვლა ზედმეტი ბიუროკრატიის გარეშე. კომპანიის ციფრული არხები განსაკუთრებით მოსახერხებელია მაშინ, როცა მარშრუტზე ოპერატიული ინფორმაცია გჭირდება.</p><p>ჩვენი ტერმინალიდან CityBus განსაკუთრებით აქტუალურია ბათუმისა და ქუთაისის მიმართულებებზე. ეს ორი ქალაქი საქართველოს შიდა გადაადგილების ყველაზე აქტიურ წერტილებს შორისაა, ამიტომ კომფორტული და გასაგები სერვისი აქ დიდ მნიშვნელობას იძენს.</p><ul><li>ორი მოთხოვნადი შიდა მიმართულება: ბათუმი და ქუთაისი</li><li>მარტივი ციფრული კომუნიკაცია და განახლებების ნახვა</li><li>კომფორტული არჩევანი მოკლე თუ საშუალო მანძილის მგზავრობისთვის</li></ul><p>თუ შენთვის მნიშვნელოვანია სწრაფი დაგეგმვა და მკაფიო სერვისი, CityBus კარგი პარტნიორია თბილისიდან დასავლეთ საქართველოსკენ მგზავრობისას.</p><p><a href="https://citybus.ge/" target="_blank" rel="noopener noreferrer">ოფიციალური ვებგვერდი</a></p>',
                'content_en' => '<p>CityBus is one of those partners that helps passengers make a travel decision quickly: check the route, review the latest information, and plan the trip without unnecessary friction. Its digital channels are useful when you want fast access to updates before departure.</p><p>From our terminal, CityBus is especially relevant for Batumi and Kutaisi. Both cities are major domestic travel points in Georgia, which makes clear service and comfortable planning especially valuable.</p><ul><li>Two busy domestic destinations: Batumi and Kutaisi</li><li>Simple digital communication and easy access to updates</li><li>A comfortable option for short and medium-distance travel</li></ul><p>If fast planning and a clear service flow matter to you, CityBus is a strong option for travel from Tbilisi toward western Georgia.</p><p><a href="https://citybus.ge/" target="_blank" rel="noopener noreferrer">Official website</a></p>',
                'content_ru' => '<p>CityBus — один из тех партнеров, которые помогают пассажиру быстро принять решение о поездке: посмотреть маршрут, проверить актуальную информацию и спланировать выезд без лишних сложностей. Цифровые каналы компании удобны, когда перед отправлением нужны свежие обновления.</p><p>Из нашего терминала CityBus особенно актуален на направлениях Батуми и Кутаиси. Оба города входят в число самых востребованных внутренних направлений, поэтому понятный сервис и комфортное планирование здесь особенно важны.</p><ul><li>Два популярных внутренних направления: Батуми и Кутаиси</li><li>Простая цифровая коммуникация и быстрый доступ к обновлениям</li><li>Комфортный вариант для коротких и средних поездок</li></ul><p>Если вам важны быстрое планирование и понятный сервис, CityBus — хороший вариант для поездки из Тбилиси в западную Грузию.</p><p><a href="https://citybus.ge/" target="_blank" rel="noopener noreferrer">Официальный сайт</a></p>',
                'cover_image_url' => 'cms/partners/citybus.png',
                'seo_title_ka' => 'CityBus: მარტივი და კომფორტული მგზავრობა ბათუმსა და ქუთაისში',
                'seo_title_en' => 'CityBus: Simple and comfortable travel to Batumi and Kutaisi',
                'seo_title_ru' => 'CityBus: Простая и комфортная поездка в Батуми и Кутаиси',
                'seo_description_ka' => 'CityBus-ის მოკლე მიმოხილვა ბათუმისა და ქუთაისის მიმართულებებზე, ციფრულ კომუნიკაციასა და კომფორტულ მგზავრობაზე.',
                'seo_description_en' => 'A short look at CityBus, its Batumi and Kutaisi routes, and its convenient digital-first service.',
                'seo_description_ru' => 'Краткий обзор CityBus, маршрутов в Батуми и Кутаиси и удобного цифрового сервиса компании.',
                'seo_keywords_ka' => 'CityBus, ბათუმი, ქუთაისი, თბილისი, ავტობუსი, შიდა რეისი',
                'seo_keywords_en' => 'CityBus, Batumi, Kutaisi, Tbilisi, domestic route, bus',
                'seo_keywords_ru' => 'CityBus, Батуми, Кутаиси, Тбилиси, автобус, внутренний маршрут',
                'seo_image_url' => 'cms/partners/citybus.png',
                'noindex' => false,
                'author_name' => 'Buster Terminal',
                'published_at' => Carbon::create(2026, 3, 16, 12, 45, 0),
                'published' => true,
                'sort_order' => 20,
            ],
            [
                'slug' => 'metro-georgia-domestic-and-international-connections',
                'title_ka' => 'Metro Georgia: შიდა და საერთაშორისო კავშირები ერთი პარტნიორისგან',
                'title_en' => 'Metro Georgia: Domestic and international connections in one network',
                'title_ru' => 'Metro Georgia: Внутренние и международные направления в одной сети',
                'excerpt_ka' => 'Metro Georgia გამოირჩევა როგორც შიდა, ისე საერთაშორისო მიმართულებების გაერთიანებით ერთ სერვისში.',
                'excerpt_en' => 'Metro Georgia stands out by combining domestic and international travel in one service network.',
                'excerpt_ru' => 'Metro Georgia выделяется тем, что объединяет внутренние и международные поездки в одной сети.',
                'content_ka' => '<p>Metro Georgia ჩვენს ტერმინალში ერთ-ერთი ყველაზე მნიშვნელოვანი პარტნიორია მათთვის, ვინც მხოლოდ საქართველოს შიგნით კი არა, ქვეყნის გარეთაც გეგმავს გზას. კომპანიის ოფიციალური არხები საერთაშორისო მიმართულებებსა და ციფრულ მომსახურებაზე მკაფიო აქცენტს აკეთებს, რაც მგზავრს უფრო ფართო არჩევანს აძლევს.</p><p>თბილისიდან Metro Georgia-ს მნიშვნელობა განსაკუთრებით კარგად ჩანს ბათუმის, ქუთაისის, ზუგდიდის, სტამბულისა და იზმირის ხაზებზე. ასეთი კომბინაცია კარგია მაშინ, როცა ერთსა და იმავე პარტნიორში გინდა იპოვო როგორც შიდა, ისე საერთაშორისო გადაადგილების ვარიანტები.</p><ul><li>შიდა და საერთაშორისო მიმართულებები ერთ ქსელში</li><li>აქტუალური არჩევანი როგორც საქართველოს შიგნით, ისე თურქეთისკენ მგზავრობისთვის</li><li>ციფრული სერვისი რეისების წინასწარ სანახავად და დასაგეგმად</li></ul><p>თუ შენთვის პრიორიტეტია ერთ პარტნიორთან მუშაობა მრავალფეროვანი მიმართულებების გამო, Metro Georgia ამ ტერმინალის ერთ-ერთი ყველაზე მოქნილი არჩევანია.</p><p><a href="https://www.metrogeorgia.ge/about-us" target="_blank" rel="noopener noreferrer">ოფიციალური ვებგვერდი</a></p>',
                'content_en' => '<p>Metro Georgia is one of the most important partners at our terminal for travelers who need more than domestic mobility. Its official channels put clear emphasis on international destinations and digital services, giving passengers a broader planning experience.</p><p>From Tbilisi, Metro Georgia is especially relevant on routes to Batumi, Kutaisi, Zugdidi, Istanbul, and Izmir. That mix is useful when you want to rely on one familiar carrier for both domestic and cross-border travel.</p><ul><li>Domestic and international destinations in one network</li><li>Relevant for travel within Georgia and onward to Turkiye</li><li>Digital tools for checking and planning trips in advance</li></ul><p>If you value a wider route map under one trusted partner, Metro Georgia is one of the most flexible options available from this terminal.</p><p><a href="https://www.metrogeorgia.ge/about-us" target="_blank" rel="noopener noreferrer">Official website</a></p>',
                'content_ru' => '<p>Metro Georgia — один из самых важных партнеров нашего терминала для пассажиров, которым нужны не только внутренние поездки. Официальные каналы компании делают явный акцент на международных направлениях и цифровых сервисах, расширяя возможности планирования для пассажира.</p><p>Из Тбилиси Metro Georgia особенно актуален на маршрутах в Батуми, Кутаиси, Зугдиди, Стамбул и Измир. Такое сочетание удобно, когда хочется пользоваться услугами одного знакомого перевозчика и для внутренних, и для международных поездок.</p><ul><li>Внутренние и международные направления в одной сети</li><li>Актуально для поездок по Грузии и в Турцию</li><li>Цифровые инструменты для предварительного планирования рейса</li></ul><p>Если для вас важна широкая география маршрутов у одного надежного партнера, Metro Georgia — один из самых гибких вариантов на нашем терминале.</p><p><a href="https://www.metrogeorgia.ge/about-us" target="_blank" rel="noopener noreferrer">Официальный сайт</a></p>',
                'cover_image_url' => 'cms/partners/metro-georgia.jpg',
                'seo_title_ka' => 'Metro Georgia: შიდა და საერთაშორისო კავშირები ერთი პარტნიორისგან',
                'seo_title_en' => 'Metro Georgia: Domestic and international connections in one network',
                'seo_title_ru' => 'Metro Georgia: Внутренние и международные направления в одной сети',
                'seo_description_ka' => 'Metro Georgia-ის მოკლე მიმოხილვა თბილისიდან შიდა და საერთაშორისო მიმართულებებზე, მათ შორის სტამბულისა და იზმირის ხაზებზე.',
                'seo_description_en' => 'A short overview of Metro Georgia on domestic and international routes from Tbilisi, including Istanbul and Izmir.',
                'seo_description_ru' => 'Краткий обзор Metro Georgia на внутренних и международных маршрутах из Тбилиси, включая Стамбул и Измир.',
                'seo_keywords_ka' => 'Metro Georgia, თბილისი, სტამბული, იზმირი, ბათუმი, ქუთაისი, ზუგდიდი',
                'seo_keywords_en' => 'Metro Georgia, Tbilisi, Istanbul, Izmir, Batumi, Kutaisi, Zugdidi',
                'seo_keywords_ru' => 'Metro Georgia, Тбилиси, Стамбул, Измир, Батуми, Кутаиси, Зугдиди',
                'seo_image_url' => 'cms/partners/metro-georgia.jpg',
                'noindex' => false,
                'author_name' => 'Buster Terminal',
                'published_at' => Carbon::create(2026, 3, 16, 12, 30, 0),
                'published' => true,
                'sort_order' => 30,
            ],
            [
                'slug' => 'luks-karadeniz-comfortable-bridge-to-turkiye',
                'title_ka' => 'Luks Karadeniz: კომფორტული ხაზი თურქეთის მიმართულებით',
                'title_en' => 'Luks Karadeniz: A comfortable bridge toward Turkiye',
                'title_ru' => 'Luks Karadeniz: Комфортный путь в сторону Турции',
                'excerpt_ka' => 'Luks Karadeniz ჩვენს ტერმინალში საერთაშორისო მგზავრობისთვის ერთ-ერთი ყველაზე საინტერესო პარტნიორია.',
                'excerpt_en' => 'Luks Karadeniz is one of the most interesting partners at our terminal for cross-border travel.',
                'excerpt_ru' => 'Luks Karadeniz — один из самых интересных партнеров нашего терминала для международных поездок.',
                'content_ka' => '<p>Luks Karadeniz განსაკუთრებით მნიშვნელოვანია იმ მგზავრებისთვის, ვინც თბილისიდან თურქეთის მიმართულებით გეგმავს გზას. კომპანიის ოფიციალური ინფორმაცია ყურადღებას ამახვილებს სატრანსპორტო გამოცდილებასა და ქსელზე, რაც საერთაშორისო მგზავრობისას მგზავრისთვის დამატებით ნდობას ქმნის.</p><p>ჩვენი ტერმინალის კონტექსტში ეს პარტნიორი განსაკუთრებით აქტუალურია სტამბულის, ანკარისა და ტრაბზონის მიმართულებებზე. ასეთ მარშრუტებზე მგზავრს სჭირდება არა მხოლოდ ბილეთი, არამედ განცდა, რომ მოგზაურობა ორგანიზებულად და წინასწარ გასაგები პირობებით დაიწყება.</p><ul><li>მნიშვნელოვანი საერთაშორისო მიმართულებები თურქეთისკენ</li><li>კარგი არჩევანი გრძელი გზისა და საზღვრისგადასასვლელი მგზავრობისთვის</li><li>კომფორტზე ორიენტირებული სერვისი საერთაშორისო რეისების კონტექსტში</li></ul><p>თუ გინდა თურქეთისკენ მგზავრობა ისეთი პარტნიორით დაგეგმო, რომელიც ამ ხაზზე სპეციალიზებულად გამოიყურება, Luks Karadeniz ყურადღების ღირსი არჩევანია.</p><p><a href="https://www.lukskaradeniz.com/hakkimizda" target="_blank" rel="noopener noreferrer">ოფიციალური ვებგვერდი</a></p>',
                'content_en' => '<p>Luks Karadeniz is especially relevant for travelers planning a trip from Tbilisi toward Turkiye. The company&apos;s official information highlights its transport experience and route network, which helps create extra confidence when planning an international trip.</p><p>In the context of our terminal, this partner is especially important on routes to Istanbul, Ankara, and Trabzon. On these routes, passengers need more than a ticket; they need a sense that the journey will start in an organized and predictable way.</p><ul><li>Key international destinations toward Turkiye</li><li>A strong option for long-distance and cross-border travel</li><li>Comfort-oriented service in the context of international routes</li></ul><p>If you want to plan your trip to Turkiye with a partner that clearly focuses on this corridor, Luks Karadeniz is worth considering.</p><p><a href="https://www.lukskaradeniz.com/hakkimizda" target="_blank" rel="noopener noreferrer">Official website</a></p>',
                'content_ru' => '<p>Luks Karadeniz особенно важен для пассажиров, которые планируют поездку из Тбилиси в Турцию. Официальная информация компании подчеркивает транспортный опыт и маршрутную сеть, что добавляет уверенности при подготовке международной поездки.</p><p>В контексте нашего терминала этот партнер особенно актуален на направлениях Стамбул, Анкара и Трабзон. На таких маршрутах пассажиру нужен не только билет, но и ощущение, что путешествие начнется организованно и предсказуемо.</p><ul><li>Ключевые международные направления в сторону Турции</li><li>Хороший вариант для дальних и трансграничных поездок</li><li>Ориентация на комфорт в международных рейсах</li></ul><p>Если вы хотите планировать поездку в Турцию с партнером, который явно сфокусирован на этом направлении, Luks Karadeniz заслуживает внимания.</p><p><a href="https://www.lukskaradeniz.com/hakkimizda" target="_blank" rel="noopener noreferrer">Официальный сайт</a></p>',
                'cover_image_url' => 'cms/partners/luks-karadeniz.svg',
                'seo_title_ka' => 'Luks Karadeniz: კომფორტული ხაზი თურქეთის მიმართულებით',
                'seo_title_en' => 'Luks Karadeniz: A comfortable bridge toward Turkiye',
                'seo_title_ru' => 'Luks Karadeniz: Комфортный путь в сторону Турции',
                'seo_description_ka' => 'Luks Karadeniz-ის მოკლე მიმოხილვა თბილისიდან სტამბულის, ანკარისა და ტრაბზონის მიმართულებებზე.',
                'seo_description_en' => 'A short overview of Luks Karadeniz on routes from Tbilisi to Istanbul, Ankara, and Trabzon.',
                'seo_description_ru' => 'Краткий обзор Luks Karadeniz на маршрутах из Тбилиси в Стамбул, Анкару и Трабзон.',
                'seo_keywords_ka' => 'Luks Karadeniz, სტამბული, ანკარა, ტრაბზონი, თურქეთი, საერთაშორისო რეისი',
                'seo_keywords_en' => 'Luks Karadeniz, Istanbul, Ankara, Trabzon, Turkiye, international route',
                'seo_keywords_ru' => 'Luks Karadeniz, Стамбул, Анкара, Трабзон, Турция, международный маршрут',
                'seo_image_url' => 'cms/partners/luks-karadeniz.svg',
                'noindex' => false,
                'author_name' => 'Buster Terminal',
                'published_at' => Carbon::create(2026, 3, 16, 12, 15, 0),
                'published' => true,
                'sort_order' => 40,
            ],
            [
                'slug' => 'tkt-ge-digital-ticketing-for-everyday-travel',
                'title_ka' => 'TKT.ge: როცა ბილეთის ყიდვა ონლაინ უფრო მარტივია',
                'title_en' => 'TKT.ge: When online ticketing makes travel easier',
                'title_ru' => 'TKT.ge: Когда онлайн-покупка билета делает поездку проще',
                'excerpt_ka' => 'TKT.ge ციფრული ბილეთინგის პლატფორმაა, რომელიც შერჩეულ მარშრუტებზე ბილეთის პოვნასა და ყიდვას ამარტივებს.',
                'excerpt_en' => 'TKT.ge is a digital ticketing platform that makes it easier to find and buy tickets on selected routes.',
                'excerpt_ru' => 'TKT.ge — цифровая билетная платформа, которая упрощает поиск и покупку билетов на выбранные маршруты.',
                'content_ka' => '<p>TKT.ge ჩვენი პარტნიორების სიაში განსხვავებული როლით ჩანს: ეს არ არის მხოლოდ გადამზიდავი, არამედ პლატფორმა, რომელიც მგზავრს ბილეთის მოძიებასა და შეძენას უმარტივებს. ოფიციალური კომპანიის აღწერა სწორედ ციფრულ გამოცდილებაზე და მარტივ ონლაინ სერვისზე ამახვილებს ყურადღებას.</p><p>თბილისის ცენტრალური ავტოსადგურის მომხმარებლისთვის ეს განსაკუთრებით მოსახერხებელია მაშინ, როცა შერჩეულ შიდა და საერთაშორისო მიმართულებებს ერთ სივრცეში ათვალიერებ. კახეთი, ბორჯომი, ერევანი და სხვა მიმართულებები სწორედ იმ ტიპის არჩევანია, სადაც სწრაფი ონლაინ შეძენა რეალურ დროს ზოგავს.</p><ul><li>ციფრული ბილეთინგის პლატფორმა სხვადასხვა მიმართულებისთვის</li><li>მარტივი შედარება და სწრაფი ონლაინ შეძენა</li><li>მოსახერხებელი არჩევანი შიდა და საერთაშორისო რეისების ნაწილზე</li></ul><p>თუ გინდა ჯერ მოძებნო, შეადარო და შემდეგ სწრაფად იყიდო ბილეთი, TKT.ge ერთ-ერთი ყველაზე პრაქტიკული ციფრული ინსტრუმენტია ჩვენი ტერმინალის კონტექსტში.</p><p><a href="https://company.tkt.ge/en/about-company/" target="_blank" rel="noopener noreferrer">ოფიციალური ვებგვერდი</a></p>',
                'content_en' => '<p>TKT.ge plays a different role in our partner lineup: it is not only about transportation itself, but about making ticket discovery and purchase simpler. The official company description highlights digital experience and a straightforward online service model.</p><p>For passengers at Tbilisi Central Bus Terminal, that is especially useful when reviewing selected domestic and international destinations in one place. Kakheti, Borjomi, Yerevan, and other routes are the kind of options where fast online purchase saves real time.</p><ul><li>Digital ticketing platform for selected routes</li><li>Simple comparison and quick online purchase</li><li>A convenient option across domestic and international travel categories</li></ul><p>If you prefer to search, compare, and then buy your ticket quickly, TKT.ge is one of the most practical digital tools connected to our terminal ecosystem.</p><p><a href="https://company.tkt.ge/en/about-company/" target="_blank" rel="noopener noreferrer">Official website</a></p>',
                'content_ru' => '<p>TKT.ge выполняет в списке наших партнеров особую роль: это не только про саму перевозку, но и про упрощение поиска и покупки билета. Официальное описание компании делает акцент на цифровом опыте и понятной онлайн-модели обслуживания.</p><p>Для пассажиров Тбилисского центрального автовокзала это особенно удобно, когда нужно посмотреть выбранные внутренние и международные направления в одном месте. Кахетия, Боржоми, Ереван и другие направления — именно тот случай, когда быстрая онлайн-покупка действительно экономит время.</p><ul><li>Цифровая билетная платформа для выбранных маршрутов</li><li>Простое сравнение и быстрая онлайн-покупка</li><li>Удобный вариант для внутренних и международных поездок</li></ul><p>Если вам важно сначала найти и сравнить варианты, а затем быстро купить билет, TKT.ge — один из самых практичных цифровых инструментов в экосистеме нашего терминала.</p><p><a href="https://company.tkt.ge/en/about-company/" target="_blank" rel="noopener noreferrer">Официальный сайт</a></p>',
                'cover_image_url' => 'cms/partners/tkt-ge.png',
                'seo_title_ka' => 'TKT.ge: როცა ბილეთის ყიდვა ონლაინ უფრო მარტივია',
                'seo_title_en' => 'TKT.ge: When online ticketing makes travel easier',
                'seo_title_ru' => 'TKT.ge: Когда онлайн-покупка билета делает поездку проще',
                'seo_description_ka' => 'TKT.ge-ის მოკლე მიმოხილვა როგორც ციფრული ბილეთინგის პლატფორმის, რომელიც შერჩეულ შიდა და საერთაშორისო მიმართულებებს ამარტივებს.',
                'seo_description_en' => 'A short overview of TKT.ge as a digital ticketing platform for selected domestic and international routes.',
                'seo_description_ru' => 'Краткий обзор TKT.ge как цифровой билетной платформы для выбранных внутренних и международных направлений.',
                'seo_keywords_ka' => 'TKT.ge, ბილეთი, ონლაინ შეძენა, კახეთი, ბორჯომი, ერევანი',
                'seo_keywords_en' => 'TKT.ge, online tickets, Kakheti, Borjomi, Yerevan',
                'seo_keywords_ru' => 'TKT.ge, онлайн билет, Кахетия, Боржоми, Ереван',
                'seo_image_url' => 'cms/partners/tkt-ge.png',
                'noindex' => false,
                'author_name' => 'Buster Terminal',
                'published_at' => Carbon::create(2026, 3, 16, 12, 0, 0),
                'published' => true,
                'sort_order' => 50,
            ],
        ] as $post) {
            BlogPost::query()->updateOrCreate(
                ['slug' => $post['slug']],
                $post,
            );
        }
    }
}
